blank_issues_enabled: false
contact_links:
  - name: ðŸ¤” Support question
    url: https://stackoverflow.com/questions/tagged/react-pdf
    about: This is a bug tracker, not a support forum. For usage questions, please use Discussions (see menu) or Stack Overflow ("Open" button) where there is a lot more people ready to help you out. Thanks!
